name: AI PR Review

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ai-pr-review-${{ github.event.pull_request.head.sha || github.run_id }}
  cancel-in-progress: true

jobs:
  review:
    name: Run AI PR Review (Bedrock Claude Sonnet)
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v4
      - name: AI PR Review (Bedrock via local action)
        uses: ./.github/actions/auto-reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION || 'us-east-1' }}
          # Prefer model id; fall back to inference profile ARN if you use it
          model_name: ${{ secrets.BEDROCK_MODEL_ID || secrets.BEDROCK_INFERENCE_PROFILE_ARN || 'anthropic.claude-3-sonnet-20240229-v1:0' }}
          model_temperature: ${{ vars.LLM_TEMPERATURE || '0.2' }}
          exclude_files: '*.js, *.json, *.md, *.yml, *.js.map, .node-version'

