name: code-review (disabled)
on: []
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run local AutoReviewer (Bedrock)
        uses: ./.github/actions/auto-reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          model_name: ${{ secrets.BEDROCK_INFERENCE_PROFILE_ARN }}
          model_temperature: 0
          exclude_files: '*.js, *.json, *.md, *.yml, *.js.map, .node-version'
